### ISSUE TITLE
No FxCop analysis has been performed on this project

### ISSUE THREAD

**Issue by LegacyEbenZhang** [DanielHWe/sonar-fxcop#5]
## The error

```java
java.lang.IllegalArgumentException: No FxCop analysis has been performed on this project, 
whereas it contains cs files: Verify that you are using the latest version of the SonarQube Scanner for MSBuild, and if you do, 
please report a bug. In the short term, you can disable all FxCop rules from your quality profile to get rid of this error.
        at org.sonar.plugins.fxcop.FxCopConfiguration.checkMandatoryProperties(FxCopConfiguration.java:104)
        at org.sonar.plugins.fxcop.FxCopConfiguration.checkProperties(FxCopConfiguration.java:95)
        at org.sonar.plugins.fxcop.FxCopSensor.execute(FxCopSensor.java:69)
        at org.sonar.batch.sensor.SensorWrapper.analyse(SensorWrapper.java:57)
        at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
```

## The versions

- SonarQube 5.3
- SonarQube Scanner for MSBuild 2.2
- FxCop Plugin 1.0
- FxCop installed to the default path on the Agent
- MSBuild 14

## The scripts to run the scanner

```
SonarQube.Scanner.MSBuild.exe begin /key:"TheKey" /name:"TheName" /version:"TheVersionNum" /d:sonar.verbose=true
msbuild /m /p:configuration=Debug /t:Rebuild TheProject.sln -- after this step I can see the CodeAnalysis.xml for each dll.
SonarQube.Scanner.MSBuild.exe end
```

**Comment by LegacyEbenZhang** [comment]
Well, figured out. One of the csproj has a post-build task to delete its *.xml. Maybe need to add more information to help investigation.

**Comment by ghost** [comment]
I'm also getting the same error.
Can you tell me the fix if your fixed it?

**Comment by LegacyEbenZhang** [comment]
Mine was due to a silly post build script that deletes the CodeAnalysis.xml.  @ab50281 yours probably a different issue.

**Comment by DanielHWe** [comment]
Version 1.3 gives better output what was wrong with the parameters
